# Generated by Django 3.1.3 on 2020-11-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='lname',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
